name: Hello, World!
description: Greet someonse and record the time
author: GitHub Actions

# Define your inputs here.
inputs:
  who_to_greet:
    description: Who to greet
    required: true
    default: World

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you.

runs:
  using: docker
  image: Dockerfile
