name: Demo
run-name: Demo WF ${{ github.jobid }}

defaults:
  run:
    shell: bash

on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden

jobs:
  demo:
    name: "Demo Job"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.name }}"
