name: GitHub Actions Demo

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
    paths-ignore: 
      - .github/**
  
  pull_request:
    branches:
      - main
      
  schedule:
    - cron: "15 6 * * SUN"
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run build against'
        type: environment
        required: true
      
  
jobs:
  log_inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Environment: $ENVIRONMENT"
        env:
          ENVIRONMENT: ${{ inputs.environment }}
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }}"
      - run: echo "Name of the branch ${{ github.ref }}"
      - uses: actions/checkout@v4
        with: 
          repository: 'mmouchous-ledger/ledger-ghactions-training'
      - run: tree .
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "Testing..."
          sleep 15
          
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo Step 1 deploying...
          sleep 10
      - run: |
          echo Step 2 deploying...
          sleep 10
      - run: |
          echo Step 3 deploying...
          sleep 10
