name: GitHub Actions Demo

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
    paths-ignore: 
      - ./.github/**
  
  pull_request:
    branches:
      - main
      
  schedule:
    - cron: "15 6 * * SUN"
  
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }}"
