name: GitHub Actions Demo

defaults:
  run:
    shell: bash
    
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - hello-world-docker-action/action.yml

jobs:
  do:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./hello-world-docker-action
      - run: echo "hello"