name: GitHub Actions Demo

defaults:
  run:
    shell: bash
    
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - hello-world-docker-action/action.yml

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: hellowith
        uses: ./hello-world-docker-action
        with: 
          who-to-greet: mememe
      - id: hellowithout
        uses: ./hello-world-docker-action
      - run: echo "hello was @ ${{ steps.hellowith.outputs.time }} and @ ${{ steps.hellowithout.outputs.time }}"