name: GitHub Actions Demo

on: 
  workflow_dispatch:
  push:
    branches:
        - main

jobs:
    do:
        runs-on: unbuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./hello-world-docker-actions
            