name: Reusable workflow

on:
  workflow_call:
    inputs: 
      who_to_greet: 
        description: 'People name'
        type: string
        required: true
        default: World

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.current_time }}
    steps:
      - name: Greet people
        run: echo "Hello $WHO_TO_GREET"
        env:
          WHO_TO_GREET: ${{ inputs.who_to_greet }}
      - name: Set time
        id: time
        run: echo "current_time=$(date)" >> GITHUB_OUTPUT
    
