name: Reusable workflow

on:
  workflow_call:
    inputs: 
      who_to_greet: 
        description: 'People name'
        type: string
        required: true
        default: World
        
  workflow_dispatch:
    inputs: 
      who_to_greet: 
        description: 'People name'
        type: string
        required: true
        default: World

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello $INPUTS_WHO_TO_GREET"
    
