name: Reuse other workflkow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who_to_greet: ${{ github.actor }}
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "current-time ${{ needs.call-workflow.outputs.current-time }}"
